### ISSUE TITLE
Handle non-json response from KP

### ISSUE THREAD

**Issue by Cameron-Kurotori** [IBM/redstone#3]
When KP returns a non-json response (usually `503 Service Unavailable` or `429 Too Many Requests`), this code will break. It may be better to handle it more cleanly by catching `JSONDecodeError`

https://github.com/IBM/redstone/blob/e232ab6cf720c4269fc144151b43e7a6a746def6/redstone/client.py#L480-L483

**Comment by mrodden** [comment]
Oops, good catch
